### ISSUE TITLE
Remember feed position at last read toot

### ISSUE THREAD

**Issue by ghoffart** [h3poteto/whalebird-desktop#574] opened 2018-08-26 22:29 UTC
When starting Whalebird, it currently positions the feed at the newest toot. So one has two options of reading:

a) Read from newest-to-oldest: wrong order for me, as I read replies before I read the original toot. Additionally, while reading I may ask myself "did I read this before" because the app doesn’t mark my last reading position.

b) Scroll down a bunch of toots, to find where I left the app the last time, then manually go up to the newest. Cumbersome.

Many good Twitter clients offer a "remember last reading position" and just indicate like "37 new posts above this reading position". I’d suggest this behaviour, as it solves both above mentioned issues: proper chronological reading order, and I don’t have to remember the last toot I read.

**Comment by mbrichman** [comment] 2018-08-26 22:54
👍

**Comment by h3poteto** [comment] 2018-08-27 00:00
Are you saying that you would like to start reading from the last time you finished it?

**Comment by mbrichman** [comment] 2018-08-27 00:51
Exactly. That would be my number 1 feature request.

**Comment by Canorus** [comment] 2018-08-27 04:29
+1

**Comment by mbrichman** [comment] 2018-08-27 23:31
To be clearer, if the last known reading position is greater than the number of toots that can be stored in the buffer, it would scroll to the oldest unread position. See how many Twitter Mac apps work.

**Comment by Canorus** [comment] 2018-10-21 09:55
oh I heard there's some ongoing issue on: tootsuite/mastodon#7418

slightly different story but maybe we can just wait a little longer and see if they decide to make a change on server side?

**Comment by h3poteto** [comment] 2021-06-03 16:27
[memo] https://docs.joinmastodon.org/methods/timelines/markers/

**Comment by h3poteto** [comment] 2021-12-26 14:46
- [x] Home
- [x] Notification
- [ ] Mention
- [ ] DM
- [ ] Local
- [ ] Public
- [ ] Tag
- [ ] Lists

**Comment by h3poteto** [comment] 2022-04-04 13:21
Is this feature needed for other timelines? For example, do you need it for Public or List?

**Comment by sr-rolando** [comment] 2022-04-05 22:11
> Is this feature needed for other timelines? For example, do you need it for Public or List?

Personally, I can't really imagine someone trying to keep following the public timeline in all its detailed glory. Thus: No. IMHO one's own timeline is totally fine for this.

**Comment by foss-** [comment] 2022-04-07 09:23
This is mentioned in the 4.5.3 release notes, however this issue here is still open. I could not find a setting to enable this for `Home`. When reloading, I keep landing on the latest post at the top and not the last read post. What is the current state of implementation?

**Comment by h3poteto** [comment] 2022-04-07 15:40
In `Home`, this feature is disabled by default. You can enable it in Settings.
![Screenshot from 2022-04-08-00-39-37](https://user-images.githubusercontent.com/4631959/162238357-ffb51301-0408-4468-9bd8-5e5cb0f41b0e.png)

**Comment by foss-** [comment] 2022-04-07 16:10
I was looking at the wrong preferences. I was pressing `⌘,` which is the preferences and was not aware there was an additional per account preferences at the top right of the timeline. Thanks for clarifying and thanks or this important feature.

**Comment by h3poteto** [comment] 2022-04-10 07:05
I can't do it for DM.
DirectMessages API returns Conversation objects, but Whalebird shows statuses for each conversation. It cannot control the marker.
We need to change DM timeline at first.

**Comment by foss-** [comment] 2022-04-11 09:51
Can you share what triggers a post to be considered `read`? Been testing this feature the past days and with both accounts I am using with whalebird, they seem to be "stuck" on a certain post as last read post. I click `Load more posts` scroll up, select the latest visible post and keep the app open. After re-opening whalebird I am back to the same post I was stuck on the past days. Maybe friendica related?

**Comment by h3poteto** [comment] 2022-04-13 16:11
Is it `Home` timeline? or `Notifications`?

**Comment by foss-** [comment] 2022-04-13 22:23
`Home`

**Comment by h3poteto** [comment] 2022-04-14 09:22
Answering your question, a status is marked as read when you receive a new status and you click `Load more posts`.
I can't reproduce it, probably the cause is server-side.

**Comment by foss-** [comment] 2022-04-14 09:23
Thanks for trying to reproduce. So I clicked load more posts a few times but whenever I re-open whalebird I am on the same timestamp on the `home` timeline.
Do you have an idea, what to look into server side to maybe debug this?

**Comment by h3poteto** [comment] 2022-04-14 09:35
@foss- Could you please create another issue?
I'm going to close this issue because the implementation is finished.

**Comment by foss-** [comment] 2022-04-14 09:56
Done, thanks for implementing this functionality.

**Closed** 2022-04-15 13:38 UTC
Labels: InProgress, feature
