### ISSUE TITLE
"failed to get authorize URL"

### ISSUE THREAD

**Issue by sascha-sl** [h3poteto/whalebird-desktop#554] opened 2018-08-21 18:14 UTC
## Description
Login form doesn't show up after putting in the domain, fails with "failed to get authorize URL"

## How To Reproduce
1. enter `deadinsi.de` on the login
2. press the button twice

## Your Environment
 - OS: OS X
 - Whalebird Version: 2.1.1
 - Instance: deadinsi.de

**Comment by h3poteto** [comment] 2018-08-22 11:35
I can reproduce it on `deadinsi.de`.
But I can not reproduce it on master branch of mastodon.
I don't know why faile to get authorize URL.

**Comment by serenitylabs-sascha** [comment] 2018-08-22 13:27
I'm running the last tagged version.

```
mastodon@web-0:~/live$ git status
On branch production
nothing to commit, working tree clean
mastodon@web-0:~/live$ git log
commit 7ac5151b74510aa82b07e349373bd442176e1e94 (HEAD -> production, tag: v2.4.3)
Author: Eugen Rochko <eugen@zeonfederated.com>
Date:   Wed Jul 11 11:21:27 2018 +0200

    Bump version to 2.4.3
```

**Comment by serenitylabs-sascha** [comment] 2018-08-22 13:32
The only thing it seems to request that shows up in my log is `api/v1/instance` and I don't see anything different in the response from `mastodon.social`

**Comment by h3poteto** [comment] 2018-08-23 01:16
Do you have any error logs?
May be the mastodon server says error logs.

**Comment by serenitylabs-sascha** [comment] 2018-08-25 01:37
I've had another log, this is the only thing from my IP in the access log when testing:

```
[redacted ipv6] - - [25/Aug/2018:03:35:25 +0200] "GET /api/v1/instance HTTP/2.0" 200 733 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Whalebird/2.1.0 Chrome/61.0.3163.100 Electron/2.0.7 Safari/537.36"
```

**Comment by h3poteto** [comment] 2018-08-26 23:25
I can't understand why Whalebird says an error even though the response is success.

**Comment by damongant** [comment] 2018-08-30 00:35
Specifying an ECDSA curve on the server side will break node it seems, the error itself is EPROTO when calling the apps endpoint

https://github.com/nodejs/node/issues/3692

**Comment by justinmayer** [comment] 2018-10-22 20:38
I am seeing the exact same problem on a `[...].space` domain with Whalebird 2.4.2. Other web clients, and also mobile clients, have no such problems and authenticate with this instance perfectly. There are no errors in the Mastodon app server logs or the Nginx logs. Unfortunate. 😞

**Comment by justinmayer** [comment] 2018-10-22 21:51
That's super helpful to know. Thanks for digging into it and reporting back here with your findings.

Does Whalebird/Node not support [modern TLS cipher suites](https://wiki.mozilla.org/Security/Server_Side_TLS#Modern_compatibility)? If not, why not?

**Comment by justinmayer** [comment] 2019-03-26 09:01
I haven't tried Whalebird in a few months due to this problem, but after trying again with the latest version I am happy to report that for me this issue has been resolved as of Whalebird v2.7.0 (on macOS 10.13.6 connecting to a Mastodon v2.7.x instance). 🎉

**Comment by h3poteto** [comment] 2019-03-26 09:21
Oh, that's good. Can I close this issue?

**Comment by justinmayer** [comment] 2019-03-26 09:26
Yes, I think you can close this issue. If someone comes across the problem again in the future, they can comment here so you can potentially re-open the issue if needed.

Thank you for all your work on Whalebird, Akira. Much appreciated. 今後とも宜しくお願いします！

**Closed** 2019-03-28 01:34 UTC

**Comment by EtaoinWu** [comment] 2022-12-18 16:09
I encountered the same issue. I use Mastodon (v4.7.3.0 on Windows) to connect to `pony.social`, a mastodon instance running v4.0.2+glitch ([glitch](https://github.com/glitch-soc/mastodon) is a fork that provides "additional features at the risk of potentially less stable software" \[from its [doc](https://glitch-soc.github.io/docs/)\]).

The reproduction procedure is identical to this issue. I am unfortunately not the maintainer of the instance and cannot provide server-side logs.

**Comment by EtaoinWu** [comment] 2022-12-18 16:11
> I encountered the same issue. 

Oh wait, I actually encountered #3859. I use a socks5 proxy.

**Comment by M-Rick** [comment] 2022-12-21 15:23
Same issue for me on macOS Monterey and Whalebird 4.7.3. I cannot connect to mastodon.cloud and I use no proxy in any kind. No problem with the other Mastodon clients. I use the official Mastodon application on my iPhone and Hyperspace on my Mac.

**Comment by HistoneVon** [comment] 2023-02-17 14:32
Same here Linux Mint 20.3 x86_64, Whalebird 4.7.4, mastodon.social.
