### ISSUE TITLE
"Could not authorize the code"

### ISSUE THREAD

**Issue by Cassolotl** [h3poteto/whalebird-desktop#271] opened 2018-04-28 14:12 UTC
I enter my instance (dev.glitch.social) in the "add new account" screen in the app.
It searches and finds it, and tells me to click "login", so I do.
The authorisation screen opens in my browser, and I click "authorise".
It gives me an authorisation code to enter in the app, so I cmd+A and copy it.
I paste it into the app's authorisation code text box and click "Submit".
I get the error message, "Could not authorize code".

**Comment by Cassolotl** [comment] 2018-04-28 14:16
I had this problem with dev.glitch.social and ephemeral.glitch.social, but not lgbt.io or mastodon.social. Ephemeral runs vanilla *mostly*. So I feel like this might be something @beatrix-bitrot should know about?

**Comment by SinaCutie** [comment] 2018-04-28 14:57
I can confirm that this doesn't work on cutie.space either (we use glitch-soc).

**Comment by h3poteto** [comment] 2018-05-10 23:53
I can confirm too.
I will try to search the cause, but it is required my mastodon server, so please wait a little more.

**Comment by h3poteto** [comment] 2018-05-12 07:04
I created an issue:
https://github.com/tootsuite/mastodon/issues/7455

**Comment by h3poteto** [comment] 2018-05-12 16:59
The issue is closed, and `doorkeeper`is downgraded. So the master branch of mastodon, it is fixed.
Please ask the administrator of `glitch.social` to update mastodon source code.

I close this issue.

**Closed by h3poteto** 2018-05-12 16:59 UTC

**Comment by Cassolotl** [comment] 2018-05-12 17:49
Thanks! :) Bea keeps the glitches pretty up to date, so hopefully it won't be long.
